GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE0LCJuYW1lIjoiSnVhbmc2NjYiLCJlbWFpbCI6ImdlZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjUxNTg4ODM5LCJleHAiOjE2NTE1ODg4NTl9.SQurCpPVz2wEcGyfJW4--o9RxmGg3sX5raGo6qxphV8

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Juang666",
    "email": "geemail@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "geemail@gmail.com",
    "password": "123456"
}